//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKICMP.schoolwork
{


    public partial class StudentActPersonManage
    {

        /// <summary>
        /// form1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.DropDownList ddl_ActType;

        protected global::System.Web.UI.WebControls.TextBox txt_ActName;

        protected global::System.Web.UI.WebControls.TextBox txt_BeginDate;

        protected global::System.Web.UI.WebControls.TextBox txt_EndDate;

        protected global::System.Web.UI.WebControls.Repeater rp_List;

        protected global::System.Web.UI.HtmlControls.HtmlTableRow tr_null;

        protected global::GKICMP.webcontrols.WebPager Pager;
    }
}
